#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_health_check:
  path: /api/v1/health-check
  controller: App\Api\HealthCheckAction
  methods: [GET]

api_register:
  path: /api/v1/users/register
  controller: App\Api\User\RegisterAction
  methods: [POST]
